### ISSUE TITLE
Set up CI? 

### ISSUE THREAD

**Issue by jpiaskowski** [NCCC170/nccc170-website#3]
Should we consider deploying this with GitHub/CI rather than netlify? I can write up a GHA.

**Comment by jarad** [comment]
What are the Pros/Cons you see for using GitHub/CI vs Netlify? I'm open to the idea of using GitHub/CI instead of Netlify. Should we start with deploying to both?

**Comment by jpiaskowski** [comment]
I personally like "github.io" along with the repo name, and think it looks professional, but the response from the group was that they have a different POV, so, I recommend you keep it as is under the "if ain't broke..." principle.
