### ISSUE TITLE
renv? 

### ISSUE THREAD

**Issue by jpiaskowski** [NCCC170/nccc170-website#4]
Should we initiative an renv.lock file to avoid compatibility issues?

**Comment by jarad** [comment]
I'm not sure it is necessary at this point. The code for the site was generated using [blogdown](https://bookdown.org/yihui/blogdown/) and following [these instructions](https://www.apreshill.com/blog/2020-12-new-year-new-blogdown/), but now there is no R being utilized.

**Comment by jpiaskowski** [comment]
I think this is important when collaborating with others, especially for a blogdown-based website so we don't have to deal with untimely update/breaking changes to R or blogdown (since the site was build with blogdown, it's using R). Setting up renv is very easy, and I recommend it be run on your end, since the sight was build by your machine. That way, other can pull site, and make PR's that will work across systems. I'm happy to meet over zoom/teams/etc.

**Comment by jpiaskowski** [comment]
bumping this

**Comment by AaronRendahl** [comment]
I hadn't seen renv before, but it looks like something I need for my own projects, even when I'm only collaborating with future me. :) I had been working on some code to automatically make pages for each talk and link them with the authors, it mostly works but I got a little carried away playing with Hugo so didn't wrap it up enough to have anyone else try it. If it's interesting to anyone who reads this, let me know and I'll see if I can push it somewhere. Anyway, if we move in that direction, this would be more important. (Though as you mention, even the bookdown compatibility could easily break).

**Comment by jpiaskowski** [comment]
If you want, I can fork, set up renv, and submit a PR. I think it might be better to do this on the original computer that built the site so nothing breaks. I am more than happy to walk someone through this (or you can follow instructions [here](https://rstudio.github.io/renv/articles/renv.html), which are largely straightforward).

**Comment by AaronRendahl** [comment]
I think that'd be fine, but that's really Jarad's call, he's the original builder.

**Comment by jpiaskowski** [comment]
I'm just trying to contribute without breaking the build.

**Comment by AaronRendahl** [comment]
Reopening this, as my code that builds the pages for the talks and authors should probably use renv. I still haven't really looked into it though. :/

**Comment by jpiaskowski** [comment]
You can do this by opening the project, installing 'renv' and running:

```
renv::init()
renv::snapshot()
```

And pushing your changes. This will create some files and directories for R versioning and package management. Everytime the project is opened, renv will automatically check to see if the system being used to open the project (e.g. a desktop computer) is consistent with the lockfile renv has on record. @AaronRendahl should do this since he wrote all the functions and we know they work on his system.

**Comment by jarad** [comment]
I agree that it makes sense for @AaronRendahl to do it.

**Comment by AaronRendahl** [comment]
Well, that was easy. Thanks @jpiaskowski for the instructions!
